spring:
  application:
    name: seed
  profiles:
    active: @build.profile.id@
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

mybatis:
  mapper-locations: classpath*:com/wping/seed/dao/mapping/**/*.xml

thread:
  pool:
    corePoolSize: 8
    maxPoolSize: 16
    queueCapacity: 200
    keepAliveSeconds: 300
    allowCoreThreadTimeOut: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-runtime-dialect: true
