server:
  servlet:
    context-path: /${spring.application.name}

spring:
  shardingsphere:
    datasource:
      names: dss-m1
      dss-m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dss?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: root
        maxActive: 30
        initialSize: 5
        minIdle: 5
        maxWait: 6000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filters: config,stat,log4j

    props:
      sql:
        show: true

  # redis sentinel 配置
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms
    database: 0
    sentinel:
      master: master
      nodes: node1:8001
    password: pwd

wping:
  # redis 相关配置信息
  redis:
    # redis key 前缀，每个系统模块锁前缀不同，防止key键冲突
    prefix: "seed:"
  redis-cache:
    enabled: true
    # cache 缓存默认时间
    default-cache-time: 600s
    cache-names:
    - name: common
      cache-time: 120s

http:
  client:
    #最大连接数
    maxTotal: 100
    #并发数
    defaultMaxPerRoute: 20
    #创建连接的最长时间
    connectTimeout: 5000
    #从连接池中获取到连接的最长时间
    connectionRequestTimeout: 5000
    #数据传输的最长时间
    socketTimeout: 30000
    proxyHost: 127.0.0.1









