spring:
  application:
    name: seed
  profiles:
    active: @build.profile.id@
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  # 同一容器部署多springboot实例
  jmx:
    default-domain: ${spring.application.name}
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath*:com/wping/seed/dao/mapping/**/*.xml

thread:
  pool:
    corePoolSize: 8
    maxPoolSize: 16
    queueCapacity: 200
    keepAliveSeconds: 300
    allowCoreThreadTimeOut: true

pagehelper:
  helper-dialect: mysql
  # 2). reasonable
  # 默认false禁用 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 3). support-methods-arguments
  # 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  # 使用方法可以参考测试代码中的 com.github.pagehelper.test.basic 包下的 ArgumentsMapTest 和 ArgumentsObjTest。
  support-methods-arguments: true
  # 4). params
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
  params: count=countSql
  # 5). auto-runtime-dialect
  # 默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页 （不支持自动选择sqlserver2012，只能使用sqlserver）。
  auto-runtime-dialect: true
